spring:
  application:
    name: action-springboot
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/action?serverTimezone=Asia/Seoul
    username: root
    password: 0000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create #db ??? ??. ?? ??? ?? ? ??
    database-platform: org.hibernate.dialect.MySQLDialect